import { ProgressLocation } from 'vscode';
import type { Container } from '../container';
import { showGenericErrorMessage } from '../messages';
import type { AIExplainSource } from '../plus/ai/aiProviderService';
import { command } from '../system/-webview/command';
import { showMarkdownPreview } from '../system/-webview/markdown';
import { Logger } from '../system/logger';
import { GlCommandBase } from './commandBase';

export interface ExplainChangesCommandArgs {
	diff: string;
	message: string;
	instructions?: string;
	title?: string;
	source: AIExplainSource;
}

@command()
export class ExplainChangesCommand extends GlCommandBase {
	constructor(private readonly container: Container) {
		super('gitlens.ai.explainChanges');
	}

	async execute(args: ExplainChangesCommandArgs): Promise<void> {
		try {
			const result = await this.container.ai.explainChanges(
				{
					diff: args.diff,
					message: args.message,
					instructions: args.instructions,
				},
				args.source,
				{
					progress: { location: ProgressLocation.Notification },
				},
			);

			let content = `# ${args.title ?? 'Changes'}\n`;
			if (result != null) {
				content += `> Generated by ${result.model.name}\n\n----\n\n${result?.parsed.summary}\n\n${result?.parsed.body}`;
			} else {
				content += `> No changes found to explain.`;
			}
			void showMarkdownPreview(content);
		} catch (ex) {
			Logger.error(ex, 'ExplainChangesCommand', 'execute');
			void showGenericErrorMessage('Unable to explain changes');
		}
	}
}
