import type { TextEditor, Uri } from 'vscode';
import { ProgressLocation } from 'vscode';
import type { Container } from '../container';
import { GitUri } from '../git/gitUri';
import { showGenericErrorMessage } from '../messages';
import type { AIExplainSource } from '../plus/ai/aiProviderService';
import { ReferencesQuickPickIncludes, showReferencePicker } from '../quickpicks/referencePicker';
import { getBestRepositoryOrShowPicker } from '../quickpicks/repositoryPicker';
import { command } from '../system/-webview/command';
import { showMarkdownPreview } from '../system/-webview/markdown';
import { Logger } from '../system/logger';
import { GlCommandBase } from './commandBase';
import { getCommandUri } from './commandBase.utils';
import type { CommandContext } from './commandContext';

export interface ExplainCommitCommandArgs {
	repoPath?: string | Uri;
	ref?: string;
	source?: AIExplainSource;
}

@command()
export class ExplainCommitCommand extends GlCommandBase {
	constructor(private readonly container: Container) {
		super('gitlens.ai.explainCommit');
	}

	protected override preExecute(context: CommandContext, args?: ExplainCommitCommandArgs): Promise<void> {
		return this.execute(context.editor, context.uri, args);
	}

	async execute(editor?: TextEditor, uri?: Uri, args?: ExplainCommitCommandArgs): Promise<void> {
		args = { ...args };
		uri = getCommandUri(uri, editor);

		const gitUri = uri != null ? await GitUri.fromUri(uri) : undefined;

		let repository;
		if (args?.repoPath != null) {
			repository = this.container.git.getRepository(args.repoPath);
		}

		repository ??= await getBestRepositoryOrShowPicker(
			gitUri,
			editor,
			'Explain Commit',
			'Choose which repository to explain a commit from',
		);

		if (repository == null) return;

		try {
			// If no ref is provided, show a picker to select a commit
			if (args.ref == null) {
				const pick = await showReferencePicker(
					repository.path,
					'Explain Commit',
					'Choose a commit to explain',
					{
						allowRevisions: true,
						include: ReferencesQuickPickIncludes.BranchesAndTags,
						sort: { branches: { current: true }, tags: {} },
					},
				);
				if (pick?.ref == null) return;
				args.ref = pick.ref;
			}

			// Get the commit
			const commit = await this.container.git.commits(repository.path).getCommit(args.ref);
			if (commit == null) {
				void showGenericErrorMessage('Unable to find the specified commit');
				return;
			}

			// Call the AI service to explain the commit
			const result = await this.container.ai.explainCommit(
				commit,
				args.source ?? { source: 'commandPalette', type: 'commit' },
				{
					progress: { location: ProgressLocation.Notification, title: 'Explaining commit...' },
				},
			);

			// Display the result
			let content = `# Commit Summary\n`;
			if (result != null) {
				content += `## ${commit.summary} (${commit.shortSha})\n> Generated by ${result.model.name}\n\n----\n\n${result?.parsed.summary}\n\n${result?.parsed.body}`;
			} else {
				content += `> No changes found to explain.`;
			}
			void showMarkdownPreview(content);
		} catch (ex) {
			Logger.error(ex, 'ExplainCommitCommand', 'execute');
			void showGenericErrorMessage('Unable to explain commit');
		}
	}
}
