import type { TextEditor, Uri } from 'vscode';
import { ProgressLocation, window } from 'vscode';
import type { Container } from '../container';
import { GitUri } from '../git/gitUri';
import type { GitStashReference } from '../git/models/reference';
import { showGenericErrorMessage } from '../messages';
import type { AIExplainSource } from '../plus/ai/aiProviderService';
import { getBestRepositoryOrShowPicker } from '../quickpicks/repositoryPicker';
import { command } from '../system/-webview/command';
import { showMarkdownPreview } from '../system/-webview/markdown';
import { Logger } from '../system/logger';
import { GlCommandBase } from './commandBase';
import { getCommandUri } from './commandBase.utils';
import type { CommandContext } from './commandContext';

export interface ExplainStashCommandArgs {
	repoPath?: string | Uri;
	ref?: string;
	source?: AIExplainSource;
}

@command()
export class ExplainStashCommand extends GlCommandBase {
	constructor(private readonly container: Container) {
		super('gitlens.ai.explainStash');
	}

	protected override preExecute(context: CommandContext, args?: ExplainStashCommandArgs): Promise<void> {
		return this.execute(context.editor, context.uri, args);
	}

	async execute(editor?: TextEditor, uri?: Uri, args?: ExplainStashCommandArgs): Promise<void> {
		args = { ...args };
		uri = getCommandUri(uri, editor);

		const gitUri = uri != null ? await GitUri.fromUri(uri) : undefined;

		const repository = await getBestRepositoryOrShowPicker(
			gitUri,
			editor,
			'Explain Stash',
			'Choose which repository to explain a stash from',
		);
		if (repository == null) return;

		try {
			let stashRef: GitStashReference | undefined;

			// If no ref is provided, show a picker to select a stash
			if (args.ref == null) {
				// Get the stash
				const stashService = repository.git.stash();
				if (stashService?.getStash === undefined) {
					void showGenericErrorMessage('Unable to get stash service');
					return;
				}

				const stash = await stashService.getStash();
				if (stash == null) {
					void showGenericErrorMessage('No stashes found');
					return;
				}

				// Use the container's instance to get a stash reference
				const stashItems = Array.from(stash.stashes.values());
				if (stashItems.length === 0) {
					void showGenericErrorMessage('No stashes found');
					return;
				}

				// If there's only one stash, use it directly
				if (stashItems.length === 1) {
					stashRef = stashItems[0];
				} else {
					// Show a quick pick to select a stash
					const items = stashItems.map(stash => ({
						label: `${stash.stashName}: ${stash.message || ''}`,
						description: stash.formattedDate || '',
						stash: stash,
					}));

					const pick = await window.showQuickPick(items, {
						placeHolder: 'Choose a stash to explain',
						ignoreFocusOut: true,
					});

					if (pick == null) return;
					stashRef = pick.stash;
				}
			} else {
				// Get the stash by ref
				const stashService = repository.git.stash();
				if (stashService?.getStash === undefined) {
					void showGenericErrorMessage('Unable to get stash service');
					return;
				}

				const stash = await stashService.getStash();
				if (stash == null) {
					void showGenericErrorMessage('No stashes found');
					return;
				}

				// Find the stash with the matching ref
				const stashItem = Array.from(stash.stashes.values()).find(item => item.ref === args.ref);
				if (stashItem == null) {
					void showGenericErrorMessage('Unable to find the specified stash');
					return;
				}

				stashRef = stashItem;
			}

			if (!stashRef) return;

			// Get the stash commit
			const commit = await this.container.git.commits(repository.path).getCommit(stashRef.ref);
			if (commit == null) {
				void showGenericErrorMessage('Unable to find the specified stash commit');
				return;
			}

			// Call the AI service to explain the stash
			const result = await this.container.ai.explainCommit(
				commit,
				args.source ?? { source: 'commandPalette', type: 'stash' },
				{
					progress: { location: ProgressLocation.Notification, title: 'Explaining stash...' },
				},
			);

			// Display the result
			let content = `# Stash: ${stashRef.message || stashRef.ref}\n`;
			if (result != null) {
				content += `> Generated by ${result.model.name}\n\n----\n\n${result?.parsed.summary}\n\n${result?.parsed.body}`;
			} else {
				content += `> No changes found to explain.`;
			}
			void showMarkdownPreview(content);
		} catch (ex) {
			Logger.error(ex, 'ExplainStashCommand', 'execute');
			void showGenericErrorMessage('Unable to explain stash');
		}
	}
}
